framework:
    rate_limiter:
        # Limiter for anonymous users (based on IP)
        anonymous_api:
            policy: 'fixed_window'
            limit: 10000
            interval: '1 minute'

        # Default limiter for authenticated users (will be overridden by user attribute)
        authenticated_api:
            policy: 'fixed_window'
            limit: 100000
            interval: '1 minute'
