security:
    role_hierarchy:
        ROLE_AUTHOR: [ ROLE_MEMBER ]
        ROLE_EDITOR: [ ROLE_AUTHOR ]
        ROLE_ADMIN: [ ROLE_EDITOR ]

    password_hashers:
        App\Entity\User: 'auto'

    providers:
        users:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

        main:
            pattern: ^/auth$
            stateless: true
            json_login:
                check_path: /auth
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

    access_control:
        # 1. Accès public aux pages de base et à la documentation (non /api)
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/api/docs, roles: PUBLIC_ACCESS }
        - { path: ^/auth, roles: PUBLIC_ACCESS }

        # 2. Accès public aux ROUTES API spécifiques (exceptions à l'authentification)
        - { path: ^/api/users, roles: PUBLIC_ACCESS, methods: [ POST ] }
        - { path: ^/api/movies, roles: PUBLIC_ACCESS, methods: [ GET ] }
        - { path: ^/api/actors, roles: PUBLIC_ACCESS, methods: [ GET ] }
        - { path: ^/api/directors, roles: PUBLIC_ACCESS, methods: [ GET ] }
        - { path: ^/api/categories, roles: PUBLIC_ACCESS, methods: [ GET ] }

        # 3. Routes admin
        - { path: ^/api/users, roles: ROLE_ADMIN, methods: [ GET, PATCH, DELETE ] }

        # 4. Toutes les AUTRES routes API nécessitent une authentification (règle générale)
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

#    access_control:
#        # Garder seulement ces 3 lignes
#        - { path: ^/$, roles: PUBLIC_ACCESS }
#        - { path: ^/api/docs, roles: PUBLIC_ACCESS }
#        - { path: ^/auth, roles: PUBLIC_ACCESS }
